### 
GET http://localhost:3000/api/users/5 HTTP/1.1

###
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "David Rosales",
    "email": "jdrj40@gmail.com",
    "password": "123456789"
}

###
POST http://localhost:3000/api/auth HTTP/1.1
Content-Type: application/json

{
  "email": "Dav1id@gmai.com",
  "password": "123456789"
}
###
POST http://localhost:3000/api/genders/save HTTP/1.1
Content-Type: application/json

{
  "name_gdr": "drama"
}
###
POST http://localhost:3000/api/movies/save HTTP/1.1
Content-Type: application/json

{
  "name_mve": "toy story 2",
  "duration": 120,
  "gender": 2,
  "image_mve": "Toy Story"
}
###
GET http://localhost:3000/api/salestickets/getByUser/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJEYXYxaWRAZ21haS5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsInJvbGUiOjEsImlhdCI6MTY3MTA3OTI4MH0.Ax2s9Dsf_t3D7-QoK6G2EWEFFss1KdiCex2sc4UyPTY HTTP/1.1


###
GET http://localhost:3000/api/movies/all HTTP/1.1


###
PUT http://localhost:3000/api/users/forgotpasswd HTTP/1.1
Content-Type: application/json

{
  "email_usr": "jdrj40@gmail.com"
}